---
deployment:
  tasks:
    - /usr/bin/rsync -a --exclude=.git --exclude=.env --exclude=storage --exclude=vendor --exclude=node_modules --exclude=bootstrap/cache --exclude=error_log /home/prestig5/repositories/chantal/ /home/prestig5/public_html/
    - /bin/touch /home/prestig5/deploy_ok.txt
    - /usr/local/bin/php /home/prestig5/public_html/artisan migrate --force || true
    - /usr/local/bin/php /home/prestig5/public_html/artisan optimize:clear || true
